### ISSUE TITLE
Circle CI fails due to encoding errors

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#151]
CircleCI started to fail with errors due to encoding collation.

```
Failures:

  1) AnthologiesController#clone when html format creates new anthology and redirects to it
     Failure/Error: unless record.user.anthologies.where("title = '#{record.title}' #{extra_cond}").empty?
     
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_bin,COERCIBLE) for operation '=': SELECT  1 AS one FROM `anthologies` WHERE `anthologies`.`user_id` = 57 AND (title = 'עותק של Anthology 5' ) LIMIT 1
     # ./app/models/anthology.rb:5:in `validate'
     # ./app/controllers/anthologies_controller.rb:35:in `clone'
     # ./spec/controllers/anthologies_controller_spec.rb:52:in `block (3 levels) in <top (required)>'
     # ./spec/controllers/anthologies_controller_spec.rb:58:in `block (5 levels) in <top (required)>'
     # ./spec/controllers/anthologies_controller_spec.rb:58:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Mysql2::Error:
     #   Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_bin,COERCIBLE) for operation '='
     #   ./app/models/anthology.rb:5:in `validate'

  2) AnthologiesController#clone when js format creates new anthology and renders js script
     Failure/Error: unless record.user.anthologies.where("title = '#{record.title}' #{extra_cond}").empty?
     
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_bin,COERCIBLE) for operation '=': SELECT  1 AS one FROM `anthologies` WHERE `anthologies`.`user_id` = 58 AND (title = 'עותק של Anthology 6' ) LIMIT 1
     # ./app/models/anthology.rb:5:in `validate'
     # ./app/controllers/anthologies_controller.rb:35:in `clone'
     # ./spec/controllers/anthologies_controller_spec.rb:52:in `block (3 levels) in <top (required)>'
     # ./spec/controllers/anthologies_controller_spec.rb:69:in `block (5 levels) in <top (required)>'
     # ./spec/controllers/anthologies_controller_spec.rb:69:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Mysql2::Error:
     #   Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_bin,COERCIBLE) for operation '='
     #   ./app/models/anthology.rb:5:in `validate'

Finished in 1 minute 2.65 seconds (files took 6.43 seconds to load)
239 examples, 2 failures
```
